### ISSUE TITLE
Provide a function to retrieve a plain url of a download 

### ISSUE THREAD

**Issue by delijati** [QMatrixClient/libqmatrixclient#168]
In the Ubuntu Touch SDK [1] is nice integration to retrieve a download. I know there is already a `FileTransferInfo` and in my other application [2] the download is handled by itself, but the data is used only for internal usage. So i would rather use the `DowloadManager` as the data is external data and should be stored in `Downloads`.

[1] https://api-docs.ubports.com/sdk/apps/qml/Ubuntu.DownloadManager/SingleDownload.html#sdk-ubuntu-downloadmanager-singledownload
[2] https://github.com/delijati/fosdem-qml/blob/master/ui/DownloadDialog.qml

**Comment by KitsuneRal** [comment]
The same idea came to me a day earlier (I was thinking to fetch direct links from QML instead of using `Room::downloadFile`), and then I realised that it doesn't boil down to a link: I have to take the access token out of library and put it to a request header in order to properly authenticate. The download manager allows to set request headers though, so the idea starts making sense for this case.

**Comment by KitsuneRal** [comment]
The library has a design problem with this though: the only place you can practically get a constructed request is `BaseJob` - moreover, you have to have already called `BaseJob::sendRequest()` (or `BaseJob::start()`, as its external API). Before that the URL simply doesn't exist for now. The first take on redesign:
1. [ ] Make URL-constructing logic a static method of BaseJob and overload it in derived classes (blergh); we assume that download requests do not have anything in the request body (which works for Matrix CS API; it doesn't in general but we don't care)
2. [ ] Add `Room::downloadLink(const QString& eventId)` that would locate the event, pick the media id out of it and construct a full URL using the above static method in `DownloadFileJob` context.

(1) looks terrible, but the fact is that currently the proto-URL is made in a respective job constructor, which means that one has to create the respective job object - a `QObject`, for a minute - to get access to a simple string concatenation/substitution. So this has to be changed anyway.

Further thoughts on the topic: more than a year ago I went out to refactor `BaseJob` so that we don't have plenty of different jobs but rather had a compact request object, a request runner (the only `QObject` for the whole array of Matrix CS API requests) and a way to connect to that runner in a type-safe way in order to process the reply. After several iterations the thing still wasn't good enough (see `kitsune-server-call` and `kitsune-server-call2` branches if interested) and at some point in time I realised that I already spent too much time on that R&D without producing a good enough result; so I just picked what was easy to pick, `Query` and `Data` (now `RequestData`) classes, and left the rest in the branch. What I wanted to say is that the subject of this issue is a no-brainer in that other design because the request is uncoupled from the actual (heavy because of `QNetworkAccessManager` and `QNetworkReply` etc.) request running logic. Maybe it's time to return to that old thing and pick another bunch of code from there.

**Comment by KitsuneRal** [comment]
There's of course a simple dirty way of copy-pasting the code from `DownloadFileJob` and putting it into `Room::downloadLink()` but then that refactoring above won't happen for another year, while the technical debt will increase.

**Comment by delijati** [comment]
Thanks for looking into that issue. I was concerned that it won't be so easy. A mix of the approach in the branch `kitsune-server-call` [1] as a static method would be nice, but i'm not sure if it is necessary. 

Correct me if i'm wrong but there are not so many places (download, avatarImg [room, user], upload maybe) where we could need the explicit `url`.

To sum it up, as of lack of time and maybe also as a unnecessary code change i could life with the dirty hack of copy pasting  code from `DownloadFileJob` to `Room::downloadLink`.

[1] https://github.com/QMatrixClient/libqmatrixclient/blob/474526558d76f49ec84334068118b98ac3c402b4/jobs/joinroomjob.cpp#L52

**Comment by KitsuneRal** [comment]
Planned changes:
1. [ ] Expose path-constructing logic as a static method of _some jobs_ (namely those that don't have anything in body). This will return just a path+query string, known by this class; it will miss `baseUrl` that needs an existing connection.
2. [ ] Add `Room::downloadLink(const QString& eventId)` that would locate the event, pick the media id out of it and construct a full URL taking `baseUrl` from its connection and using the above static method in `DownloadFileJob` context.

**Comment by KitsuneRal** [comment]
3. [ ] Add similar-working `Room::thumbnailUrl(const QString& eventId)` to download thumbnails.
Note that it's still responsibility of the client to get access token from the room's connection and supply it in `Authorization` network header. See `BaseJob::Private::sendRequest()` implementation and the first paragraph in [CS API's "Client Authentication" chapter](https://matrix.org/docs/spec/client_server/r0.3.0.html#client-authentication).

**Comment by KitsuneRal** [comment]
@delijati, you can try the commit above (note that it's in the feature branch yet).

**Comment by delijati** [comment]
Tried the feature branch works like expected

**Comment by KitsuneRal** [comment]
Awesome!
