### ISSUE TITLE
Some rooms randomly get removed from m.direct

### ISSUE THREAD

**Issue by aaronraimist** [QMatrixClient/libqmatrixclient#323]
### Description

I lost most of my `m.direct` rooms a few days ago and thought it might be a Riot issue but then @spantaleev mentioned that he had the same problem with Spectral. I restarted Quaternion and again most of my rooms disappeared from the people section in Riot. Looking at Riot's /devtools, each time I restarted Quaternion it would always leave the same one room in `m.direct` but the rest would be gone.

Grep "rGAkmbsnEmSpCkfcFu" (one affected room) from the logs:
```
RoomListModel: Added "!rGAkmbsnEmSpCkfcFu:raim.ist" to group "org.qmatrixclient.direct"
RoomListModel: Removing room "!rGAkmbsnEmSpCkfcFu:raim.ist" from group "org.qmatrixclient.direct"
RoomListModel: Added "!rGAkmbsnEmSpCkfcFu:raim.ist" to group "org.qmatrixclient.none"
RoomListModel: groups for "!rGAkmbsnEmSpCkfcFu:raim.ist" updated
```

Sending full logs via Matrix.

### Version information

- **The client application**: Quaternion 0.0.9.4
- **libqmatrixclient version if you know it**: 0.5.1.2 presumably
- **Install method**: .dmg
- **Platform**: macOS 10.14.5

**Comment by KitsuneRal** [comment]
Thank for reporting - I thought it's a local glitch on my development machine but apparently it's not. I remember there's a been a nasty race condition around the code dealing specifically with `m.direct` - apparently I didn't fully fix it.

**Comment by KitsuneRal** [comment]
Ok, the situation is clear: the race condition actually is there but hasn't been observable until the library learnt to correctly deal with invites to direct chats. As for now, when the cache is clear the library will only keep direct chats where the local user has been invited and will unmark all other rooms (which were marked a direct chats later, or where the local user initiated the chat). The fix is in the works (will also be applied to 0.5.x).
