### ISSUE TITLE
room avatar events

### ISSUE THREAD

**Issue by maralorn** [QMatrixClient/libqmatrixclient#40]

**Comment by KitsuneRal** [comment]
`m.room.avatar` is identical in its structure to a `RoomMessageEvent::ImageContent`. Apparently, supporting room avatars boils down to factoring out `ImageContent` so that it could be included in an arbitrary event, not only a message event; and making a trivial `RoomEvent` subclass that would include `ImageContent`.

**Comment by KitsuneRal** [comment]
Fixed by 0fb7adfcaa5dffee4efd0a34a2a4fd655fe5c709
